classDiagram
    class Hora {
        - horas: int
        - minutos: int
        - segundos: int
        + setHoras(horas: int): void
        + getHoras(): int
        + setMinutos(minutos: int): void
        + getMinutos(): int
        + setSegundos(segundos: int): void
        + getSegundos(): int
        + coonvertir_segundos(): int
        + cnvertir_minutos(): int
        + incrementar_minutos(minuntos: int): void
        + incrementar_segundos(segundos: int): void
        + incrementar_horas(hora: int): void
        + mostrar_formato_12horas()


    }